#NUM_CLASSES = 2
IMG_SIZE = 227
FOLD_GENDER = "4"
FOLD_AGE = "1"
DATA_TYPE_GENDER = "gender"
DATA_TYPE_AGE = "age"
HOME_PATH = "/home/ubuntu/CourseProject"
SOURCE_FOLDER = "AgeGenderDeepLearning/Folds/train_val_txt_files_per_fold/test_fold_is_"
LEARNING_RATE=0.0001
LEARNING_RATE_AGE=0.00000001
BATCH_SIZE = 50
EPOCHS_AGE = 100
EPOCHS_GENDER = 25
OPTIMIZER_GENDER = 'rmsprop'
OPTIMIZER_AGE = 'rmsprop'


FOLDER_NAME_GENDER = 'TYPE_{}_LR_{}_OPTIMIZER_{}_FOLD_{}'.format(DATA_TYPE_GENDER, LEARNING_RATE, OPTIMIZER_GENDER, FOLD_GENDER)
LOG_FILE_GENDER = '{}/status.log'.format(FOLDER_NAME_GENDER)
MODEL_FILE_GENDER = '{}/model.json'.format(FOLDER_NAME_GENDER)
WEIGHT_FILE_GENDER = '{}/weights.h5'.format(FOLDER_NAME_GENDER)
NUM_LABELS_GENDER = 2

FOLDER_NAME_AGE = 'TYPE_{}_LR_{}_OPTIMIZER_{}_FOLD_{}'.format(DATA_TYPE_AGE, LEARNING_RATE, OPTIMIZER_AGE, FOLD_AGE)
LOG_FILE_AGE = '{}/status.log'.format(FOLDER_NAME_AGE)
MODEL_FILE_AGE = '{}/model.json'.format(FOLDER_NAME_AGE)
WEIGHT_FILE_AGE = '{}/weights.h5'.format(FOLDER_NAME_AGE)
NUM_LABELS_AGE = 8
